### ISSUE TITLE
Improve "Slicer Features" section

### ISSUE THREAD

**Issue by jcfr** [Slicer/slicer.org#19]
Here some suggestions to improve the Features section

## Additional "features" to list

* Supports images, segmentations, surfaces, annotations, transformations, etc., in 2D, 3D, and 4D.
* Analysis includes segmentation, registration, and various quantifications.

from @rkikinis:

* Describe approach for creating extension: lightweight in python, C++ module, SlicerCustomApp, ... 
* DICOM: Which Part ... ? Multi-frame, seg object, ... 

## Revisit organization of features

Instead of having a fixed list of text, we could organize each feature as card (without or without icon) and have a clickable link. For example:

![image](https://user-images.githubusercontent.com/219043/89447187-9b722e00-d723-11ea-8c72-8c44becc303a.png)
_Copied from https://docs.amplify.aws/_

In our case, we could describe each "feature" using syntax reported below. The challenge is that we do not consistently have a page for the user to click on.

I tentatively referenced section of the [user guide](https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html) but I think we should probably have a dedicated internal  page for each.

cc: @lassoan @pieper What do you think ? 

```
- title: DICOM standard interoperability
  description: DICOM browser allowing local import and indexing.
  link: https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html

- title: Streamlined segmentation
  description: Capabilities for 2D/3D/4D image supporting hundreds of segments per image
  link: https://slicer.readthedocs.io/en/latest/user_guide/modules/segmentations.html

- title: Artificial Intelligence
  description: AI-based automatic segmentation, tools for ground truth training data generation, DeepInfer extension for Deep Learning, Tensorflow compatibility and Nvidia Clara automatic segmentation. 
  link:

- title: 4D data support
  description: Time sequence visualization & analysis
  link: https://www.slicer.org/wiki/Documentation/Nightly/Extensions/Sequences

- title: 3D printing friendly
  description: 3D-printable mesh, volume export
  link: https://www.youtube.com/watch?v=Uht6Fwtr9hE

- title: Virtual Reality and Augmented Reality
  description: Interact with scene in HTC, Oculus, WindowsMR systems; export data to HoloLens 
  link: 

- title: Python scripting
  description: Live introspection, interface scripting, Python 3 packages can be installed 
  link: 

- title: Surgical planning and guidance
  description: Real-time data recording, analysis and replay from surgical navigation systems, ultrasound scanners cameras and trackers, OpenIGTLink connection with trackers, scanners 
  link:

- title: Cloud-based computing
  description: 3D Slicer in web browser, Docker container, or Jupyter notebook kernel 
  link:
```

## Reduce amount of text

_Originally posted by @fedorov in https://github.com/Slicer/slicer.org/pull/16#issuecomment-665747948_

> and maybe the amount of text needs to be reduced.

Comment based on preview of 2020.07.29 that was available at https://deploy-preview-16--slicer-org.netlify.app/ (https://github.com/Slicer/slicer.org/commit/0a1313b40ebc23ed2f8015b0676992fa2cffbc43)

@fedorov Could you provide suggestions here: https://docs.google.com/document/d/1MFHUKaY1K7ZjlMUT6O-L1tCj2yIhhdtzimBbL5lJrfc/edit#heading=h.jh7so2nj3dc
